##########################################################################################
# 공통
##########################################################################################
project:
  name: first-api-server
  description: API 서버

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
  error:
    whitelabel:
      enabled: false
      
spring:
  application:
    name: ${project.name}
    description: ${project.description}
    version: 1.0.0
    locale-resolver: cookie
    log-appenders:
      - console
      - file
  pid:
    file: ${app.home}/bin/shutdown.pid
  web:
    resources:
        add-mappings: false
  main:
    allow-circular-references: true
    
  cache:
    ehcache.config: classpath:ehcache.xml

############################################################################
# objectmapper properties
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"


############################################################################
# Mybatis propperties
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  check-config-location: true
  mapper-locations : classpath*:mapper/**/*.xml
  

############################################################################
# Pagehelper propperties
pagehelper:
  helper-dialect: sqlserver
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    metrics:
      enabled: true
    prometheus:
      enable: true
    web:
      exposure:
        include: "*"
  health:
    diskspace:
      enabled: false
    db:
      enabled: false
  endpoint:
      info:
        enabled: true  