##########################################################################################
# [ Local 서버 프로파일 ]
##########################################################################################
server:
  port: 9090

spring:
  jackson:
    serialization:
      indent-output: true

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:sqlserver://localhost:1433;databaseName=tempdb;encrypt=false
    username: sa
    password: "Rnfkehfl1!"
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 5
      connection-timeout: 600000

  devtools:
    restart:
      enabled : true
      livereload:
        enabled: true

