##########################################################################################
# [ prod 서버 프로파일 ]
##########################################################################################
server:
  port: 8099
  
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=tempdb;encrypt=false
    username: sa
    password: "Rnfkehfl1!"
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 5
      connection-timeout: 600000